#!/bin/env python3
import os

from bson import ObjectId
from dotenv import load_dotenv
from pymongo import MongoClient

# Load environment variables from .env file
load_dotenv(dotenv_path="/lab/.env")

# Get MongoDB URI from environment variable
uri = os.environ.get("MONGODB_URI")

# Create a MongoDB client and connect to the database
client = MongoClient(uri)
db = client["bank"]
accounts = db["accounts"]

# Query by ObjectId
document_to_delete = {"_id": ObjectId("62d6e04ecab6d8e130497485")}

# Delete the matching document
result = accounts.delete_one(document_to_delete)

# Print the result
print(f"Documents deleted: {result.deleted_count}")

# Close the MongoDB connection
client.close()
