#!/bin/env python3
import os

from bson import ObjectId
from dotenv import load_dotenv
from pymongo import MongoClient

# Load environment variables from .env file
load_dotenv(dotenv_path="/lab/.env")

# Get MongoDB URI from environment variable
uri = os.environ.get("MONGODB_URI")

# Create a MongoDB client and connect to the database
client = MongoClient(uri)
db = client["bank"]
accounts = db["accounts"]

# Query by ObjectId
document_to_delete = {"_id": ObjectId("62d6e04ecab6d8e130497485")}

# TODO: Write an expression that deletes the document matching the query constraint in the 'accounts' collection. Assign the result of the operation to a variable named 'result'.
# result =

# Print the result
print(f"Documents deleted: {result.deleted_count if result else 0}")

# Close the MongoDB connection
client.close()
